# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.luks.devices.cryptlvm.device = "/dev/disk/by-uuid/ba350db1-8066-4f16-85cb-949ccf567d05";  
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6095a57a-2048-4048-998e-122fbaae4717";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/f9bafaeb-7c00-4fb8-beda-0a45b34f4bed";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F86E-9A97";
      fsType = "vfat";
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/9fa175ce-c432-4931-81b4-216f5ddeb9f1";
      fsType = "ext4";
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-uuid/59944edd-9cbd-476e-b372-2aa825701aea";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/f3782c77-9666-4733-9ce0-217fd4d4dfc0";
      fsType = "xfs";
    };

  fileSystems."/media/backup" =
    { device = "/dev/disk/by-uuid/cd1a23fb-683f-48e8-80c8-ef2a01020340";
      fsType = "xfs";
      encrypted = {
        label = "backup";
        enable = true;
        blkDev = "/dev/disk/by-uuid/0ef6dda5-655c-4dc0-a9bb-5febc2b3cf9a";
        keyFile = "/mnt-root/.backup-keyfile";
      };
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/645db90e-ace5-41b9-adc9-f9c91a6f9537"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
