# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  # Use the GRUB 2 boot loader.
  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  boot.loader.grub.devices = [
      "/dev/disk/by-id/wwn-0x5002538e000c21b7"
      "/dev/disk/by-id/wwn-0x5002538e40de02bf"
  ];
  boot.initrd.luks.devices.cryptroot.device = "/dev/disk/by-uuid/64dbda22-7a05-4d1c-a64b-bbbc779f1bdc";
  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d8009534-e327-4c83-965d-91791736db2a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/211b4a9d-71b5-4262-9082-cac1c7a6b60b";
      fsType = "ext4";
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/7b849f20-ac8e-4158-b595-fc7fa46f713f";
      fsType = "ext4";
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-uuid/7ece83d5-9f2f-4775-8efa-c53783f3a607";
      fsType = "btrfs";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/cae3edd4-e35f-4338-ab74-d2df99fc5689";
      fsType = "ext4";
    };

  fileSystems."/gnu" =
    { device = "/dev/disk/by-uuid/8726cdc2-aeed-40f4-81b9-402b78fb14a0";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/7f348443-ac88-427a-979a-6bcc359ab47a";
      fsType = "xfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/493df1a1-83bd-4fec-8cbb-2242533751f0"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
